### PR TITLE
Cosmetic update

### PR DESCRIPTION
**Pull request by magikcypress**
I worked for a cosmetic code with a new helpers.

### CODE REVIEW

**Review by JimboJoe — APPROVED** [review]
I'm OK with this PR, thanks!
Yet I'm wondering is there are any risks with proposing this app as official as the software hasn't been updated for 5 years...

**Comment by magikcypress** [comment]
This is a good comment, I think this application is really not very interesting. Users who use the shell connect to it directly.

**Comment by magikcypress** [comment]
... and 5 years is an infinite time.

**Comment by JimboJoe** [comment]
Furthermore it's highly recommend to use RSA keys to connect to SSH; Shellinabox doesn't seem to allow this.

**Review by maniackcrudelis — APPROVED** [review]

**Comment by maniackcrudelis** [comment]
As far as I know, shellinabox doesn't provide an ssh connection, but allow to connect directly to the local terminal.
And this app doesn't propose any public access. So even if its security it's not optimal, it stays behind the SSO.

But, maybe we can add a big warning into the readme, to inform any users.

**Comment by JimboJoe** [comment]
You're damn right, that's a local connection! :-)
So provided it's behind the SSO, that seems acceptable.

**Pull request merged**
