### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Global upgrade of the package.*
- *Add a change_url script*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/shellinabox_ynh%20PR13/)
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
As discussed [here](https://github.com/YunoHost-Apps/shellinabox_ynh/pull/12#issuecomment-469816430), proposing to wait for a functional change before advertising a testing release.

**Comment by kay0u** [comment]
Change url is not a "Functional change"?

**Comment by maniackcrudelis** [comment]
Yep it is
Ready for review

**Review by kay0u — APPROVED** [review]
LGTM & code review

**Review by alexAubin — APPROVED** [review]
Trying to help this PR move forward ... Made a quick review and everything looks like small legit changes (well except for the change_url part, but it looks understandable and legit)

So, didn't test but LGTM :+1:

**Comment by kay0u** [comment]
Can be merged in 3 days?

**Comment by maniackcrudelis** [comment]
Aleks isn't a member of apps group.
But anyway, should we really wait more for an like this one...?

**Comment by kay0u** [comment]
As you are not the author of this PR, you can add a LGTM too if you want ;-)

**Comment by JimboJoe** [comment]
And I'm the author of the PR, but not of the code so... LGTM? :slightly_smiling_face:

**Comment by kay0u** [comment]
Ok, can be merged in 3 days then!

**Pull request merged**
