### PR TITLE
Package upgrade

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Global upgrade of the package.*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : kay0u
- **CI succeeded** : 
[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/shellinabox_ynh%20package_upgrade%20(Official)/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Review by kay0u — CHANGES_REQUESTED** [review]
`ynh_print_info` (min 3.2) is used since the minimum version is 2.7. maybe bump the version of yunohost, or add this helper in _common.h

**Comment by maniackcrudelis** [comment]
Just a mistake, it should be 3.2.0

**Review by kay0u — APPROVED** [review]

**Review by JimboJoe — APPROVED** [review]
LGTM and code review OK :+1:

**Comment by JimboJoe** [comment]
Can be merged in 3 days... Shall we advertise the testing releases when there is only a refactoring...? :thinking:

**Comment by maniackcrudelis** [comment]
> Shall we advertise the testing releases when there is only a refactoring...? :thinking:

I would say globally yes, because it could have regression in some huge PR with a lot of modifications.
But for an app like this one that already respect the template, there's no big changes.
So I think for such a PR, we don't need a testing.

**Pull request merged**
